services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opusdb
      MYSQL_USER: opususer
      MYSQL_PASSWORD: opuspassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - opusnet

  redis:
    image: redis:6
    networks:
      - opusnet

  opus:
    build:
      context: https://github.com/robert789i/opusprueba.git
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: opusdb
      DB_USERNAME: opususer
      DB_PASSWORD: opuspassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: local
      APP_DEBUG: true
    ports:
      - "8080:80"
    networks:
      - opusnet

volumes:
  mysql_data:

networks:
  opusnet:
